### PR TITLE
Dynamically include source property docs

### LINKED ISSUE #463: Include clustering options in documentation
The clustering options `cluster`, `clusterRadius`, and `clusterMaxZoom` are [present in the spec definition](https://github.com/mapbox/mapbox-gl-style-spec/blob/194fc55b6a7dd54c1e2cf2dd9048fbb5e836716d/reference/v8.json#L173-L186), but do not appear in the docs because `source` properties aren't included dynamically the way that root, `layer`, `layer.layout`, and `layer.paint` properties are.

Option 1: simply document the cluster\* options manually in the narrative docs.
Option 2: start including dynamically the source properties.

Option 1 is quicker, but more brittle and less complete, so fwiw I'd vote for option 2.

### PR DESCRIPTION
**Pull request by anandthakker**
Closes #463

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Example output:

image
- Saying `type` can be "One of vector, raster" in both the vector and raster source sections is misleading. Maybe omit `type` completely?
- `tileSize` is not allowed for `vector` sources, which must be 512px.

**Comment by anandthakker** [comment]
> Saying type can be "One of vector, raster" in both the vector and raster source sections is misleading. Maybe omit type completely?

Ah, whoops.  I meant to do this and forgot - thanks.

> tileSize is not allowed for vector sources, which must be 512px.

👍

**Comment by anandthakker** [comment]
@jfirebaugh ^

updated screenshot

screen shot 2016-08-26 at 7 59 39 pm

(raster still has `tileSize`)

**Comment by jfirebaugh** [comment]
Thanks!

**Pull request merged**
