### PR TITLE
add new dds line properties

### PR DESCRIPTION
**Pull request by mollymerp**
DO NOT MERGE until v0.28.0
cc @lucaswoj 
update style spec to reflect changes in https://github.com/mapbox/mapbox-gl-js/pull/3033

### CODE REVIEW

**Comment by lucaswoj** [comment]
I don't see much downside to merging this alongside the rest of the line property function PRs. It's not inaccurate to talk about the supported features of a future version 😄

**Comment by mollymerp** [comment]
OK -- I guess its just pending whether tomorrow will be 0.28 or 0.27.1

**Comment by lucaswoj** [comment]
Good point. Let's hold off until that release hits the airwaves.

**Review by lucaswoj — APPROVED** [review]
Now that the downstream PRs are merged, this is ready to 🚀

**Comment by lucaswoj** [comment]
I'm going to update this manually when the release comes out 👍

**Pull request closed without merging**
