### PR TITLE
Add support for icon-offset property functions

### PR DESCRIPTION
**Pull request by jellevoost**

### CODE REVIEW

**Comment by lucaswoj** [comment]
A quick note to trigger Github's crosslinking functionality: this is related to https://github.com/mapbox/mapbox-gl-js/pull/3729

**Comment by jfirebaugh** [comment]
`icon-offset` units are relative to `icon-size` (#84). Do we face a similar issue with making `icon-offset` data-driven as we did with `line-width` and `line-dasharray`?

cc @ansis

**Comment by ansis** [comment]
> icon-offset units are relative to icon-size (#84). Do we face a similar issue with making icon-offset data-driven as we did with line-width and line-dasharray?

Nope, because they are relative to the `icon-size` at the current zoom level.

Side note: `icon-offset` was made relative to `icon-size` in order to make it work more easily with the collision detection, not as what-is-better-externally decision.

**Comment by jfirebaugh** [comment]
Committed as f7d472426f0235ed3fe1e4721b5d68f3c171010a. Thanks!

**Pull request closed without merging**
