### PR TITLE
prevent ramp from having duplicate stops

### PR DESCRIPTION
**Pull request by mayagao**
@jfirebaugh Do I also need to create a test for this? Doesn't seem to have a test for ramps.

cc @samanpwbb

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Yes, insert a test case [here](https://github.com/mapbox/mapbox-gl-style-spec/blob/1b8a95179efc879712afe999dabc9b3ac03cb75a/test/fixture/functions.input.json#L127-L128), and then run `UPDATE=1 npm test`, which should update `functions.output.json` with the expected output.

**Comment by mayagao** [comment]
is this the right way?

**Comment by jfirebaugh** [comment]
The line number updates in `functions.output.json` are expected, but I'd also expect to see a new error with the text "array has duplicate stops" in the output. Since it's not there, for some reason the test case does not trigger the new validation. Can you try using `==` instead of `===`? The validator uses boxed types so that it can attach line numbers to them, which means that `===` comparison doesn't always work.

**Comment by mayagao** [comment]
ok updated, thank you @jfirebaugh

**Pull request merged**
