### PR TITLE
v8 Omnibus

### LINKED ISSUE #215: Rename *-image properties to *-pattern
Since `background-image`, `line-image` and `fill-image` tile the image, let's rename them to `background-pattern`, `line-pattern` and `fill-pattern`.

### LINKED ISSUE #247: centerpoint
Style objects should have a `center` key. This could be optional. If it were to follow the pattern used by the Mapbox Map API, would look like:

```
"center": [ 
  {longitude}, 
  {latitude},
  {center},
  {bearing}
]
```

### LINKED ISSUE #250: Switch to lon, lat order
* `center`
* video `coordinates`

### LINKED ISSUE #252: rename `symbol-min-distance` to `symbol-spacing`
I copied the name from carto but I copied it from the wrong property.

In carto `text-spacing` determines the distance between repeated labels on a line. `text-min-distance` does something else.

### LINKED ISSUE #257: Font stacks should be arrays
Font stacks shouldn't be strings concatenated by `,`s: this makes constants of fontstacks weird. Fontstacks should be string arrays.

### LINKED ISSUE #260: video source: url ⇢ urls
The `url` property of a video source is an array, it should be plural.

### PR DESCRIPTION
**Pull request by tmcw**
Patches:

[JS](https://github.com/mapbox/mapbox-gl-js/pull/1192), [Native](https://github.com/mapbox/mapbox-gl-native/pull/2052)

Changes

* [x] Font stacks as arrays. Fixes #257.
  * [x] JS https://github.com/mapbox/mapbox-gl-js/pull/1081
  * [x] Native https://github.com/mapbox/mapbox-gl-native/pull/993
  * [x] Spec https://github.com/mapbox/mapbox-gl-style-spec/blob/2b7c3777943049660613778e2076703c59a5aa9c/reference/v8.json#L462-L471
  * [x] Migration https://github.com/mapbox/mapbox-gl-style-spec/blob/2b7c3777943049660613778e2076703c59a5aa9c/migrations/v8.js#L44-L50
  * [x] Tests
  * [x] Styles
* [x] Permit map properties (centerpoint) Fixes #247 
  * [x] JS: no changes
  * [x] Native: no changes
  * [x] Migration: no changes
  * [x] Spec
  * [x] Styles
* [x] Rename symbol-min-distance to symbol-spacing. Fixes #252 
  * [x] JS
  * [x] Native https://github.com/mapbox/mapbox-gl-native/pull/993
  * [x] Spec https://github.com/mapbox/mapbox-gl-style-spec/blob/2b7c3777943049660613778e2076703c59a5aa9c/reference/v8.json#L315-L326
  * [x] Migration https://github.com/mapbox/mapbox-gl-style-spec/blob/2b7c3777943049660613778e2076703c59a5aa9c/migrations/v8.js#L51-L53
  * [x] Tests
  * [x] Styles
* [x] Rename video url to urls. Fixes #260 
  * [x] JS
  * [x] Native: no gl-native patch needed: video not supported
  * [x] Spec https://github.com/mapbox/mapbox-gl-style-spec/blob/2b7c3777943049660613778e2076703c59a5aa9c/reference/v8.json#L137
  * [x] Migration https://github.com/mapbox/mapbox-gl-style-spec/pull/264/files#diff-d94eefc8f1c24000ab9c6b1aa11ed555R34
  * [x] Tests
  * [x] Styles
* [x] ImageSource source type
  * [x] JS https://github.com/mapbox/mapbox-gl-js/pull/1174
  * [x] Native **shipping without** https://github.com/mapbox/mapbox-gl-native/issues/1350
  * [x] Spec
  * [x] Migration **none needed: new feature**
  * [x] Tests https://github.com/mapbox/mapbox-gl-test-suite/issues/27
  * [x] Styles
* [x] Flip coordinate order of video coordinates. Fixes #250
  * [x] JS
  * [x] Native: no gl-native patch needed: video not supported
  * [x] Spec
  * [x] Migration
  * [x] Tests
  * [x] Styles
* [x] background-image ⇢ background-pattern, line-image ⇢ line-pattern, fill-image ⇢ fill-pattern to fix #215
  * [x] JS
  * [x] Native https://github.com/mapbox/mapbox-gl-native/pull/993
  * [x] Spec
  * [x] Migration
  * [x] Tests
  * [x] Styles
* [x] Circle type
  * [x] JS https://github.com/mapbox/mapbox-gl-js/pull/1286
  * [x] Native https://github.com/mapbox/mapbox-gl-native/pull/2053
  * [x] Spec
  * [x] Tests
  * [x] Styles
* [x] Remove `text-max-size` and `icon-max-size`
  * [x] JS
  * [x] Native
  * [x] Spec https://github.com/mapbox/mapbox-gl-style-spec/issues/255
  * [x] Migration
  * [x] Tests
  * [x] Styles
* [x] Drop constants and color ops #308
  * [x] JS
  * [x] Native
  * [x] Spec
  * [x] Migration
  * [x] Tests
  * [x] Styles
* [x] Change `mapbox://` URL semantics #309
  * [x] JS
  * [x] Native
  * [x] Spec
  * [x] Migration
  * [x] Tests
  * [x] Styles
* [x] Flip label layer priority order #256
  * [x] JS
  * [x] Native
  * [x] Spec
  * [x] Migration
  * [x] Tests
  * [x] Styles

### CODE REVIEW

**Comment by tmcw** [comment]
@lbud @quinnvd one thing I've always kind of wondered about the less-style operations (we used them directly in cartocss) was that

* lighten & darken
* saturate & desaturate
* fadeout & fadein

Are basically duals: saying `saturate: 10%` means `desaturate: -10%` and you get the picture. Especially given that we'll be wrapping these in a UI, I think separating the negative and positive versions of the transform will just make downstream implementations weirder.

Thoughts?

**Comment by lbud** [comment]
@tmcw hm, true, and I see how if we use a slider UI centered at neutral this would make the implementation weird. But I also wonder if consistency from a Carto/LESS background is important.
cc @nickidlugash @samanpwbb @edenh — ?

**Comment by nickidlugash** [comment]
@lbud Personally I'm in favor of prioritizing UI implementation over consistency with carto/LESS.

**Comment by samanpwbb** [comment]
@nickidlugash @lbud regardless of how we end up doing this in the style JSON, the UI can do exactly what we want it to do. I was curious about this so I sketched it up:

https://github.com/mapbox/app-styles/issues/1352

Basically: show more fields and assume positive input values, or show less fields and assume both positive and negative input fields. Even if we include all the filters, we can still hide the 'negative' versions of the filters in the UI. I do believe if we implement a UI more like sketch 1, having both positive and negative options available would be better usability:

As a user, I know I want something to be desaturated. I'm going to look for "desaturate" first not for "negative saturate".

**Comment by tmcw** [comment]
2015-03-25 at 2 19 pm

image

**Comment by samanpwbb** [comment]
@tmcw I agree with you here, lets drop the inverse filters. It'll be simpler to implement in the UI.

**Comment by nickidlugash** [comment]
I was thinking sliders, too.

**Comment by lbud** [comment]
Ok, so we'll pick `saturate`, `lighten`, and which fade one makes more sense to be positive? (I'm instinctively inclined to say `fadein` should be positive, although I would guess that's used less frequently…)

**Comment by samanpwbb** [comment]
@lbud how about just 'fade' - positive values increase fade, negative values decrease fade?

**Comment by tmcw** [comment]
Another modification for comment:

* I think that we should support **embedded sprite metadata**: instead of pointing to a URL that contains sprite metadata, that data should be nested under the sprite key of the stylesheet.

**Comment by jfirebaugh** [comment]
> embedded sprite metadata

What's the rationale? I'm tentatively :-1: because previous discussions have pointed towards an omnibus format for sprites that combines images and metadata, which would either duplicate or obsolete style-embedded-metadata.

**Comment by tmcw** [comment]
What's the rationale?

* One fewer HTTP request to show each map
* Easier & faster to do better stylesheet validation - validate that references to the sprite are valid
* Simpler to implement in app-styles (okay, showing my hand with that one)

**Comment by incanus** [comment]
Sprite metadata in the style feels bloated. 

- We already support two pixel ratios, and might do more. Even if we handle SVG sprites, we will always do rasters of some sort and multi-DPI just makes for a messy style section. 

- To clarify @jfirebaugh's point, we've talked (https://github.com/mapbox/mapbox-gl-style-spec/issues/220) about a binary sprite storage format to reduce branching and increase performance. Being able to seek a sprite's metadata out of the store without having to pre-parse the whole store from a text format would unblock runtime sprite changes (such as a set of POI icons changing during a label language swap) or sprite attribute changes (such as toggling an icon theme as part of a POI level-of-detail change or a class toggle which affects icon style, such as color change in a night style). 

- We will invariably keep the imagery itself out of the style (base64 encoding or something similar would be a waste), so why split the imagery and metadata? One less HTTP request doesn't feel like a level trade given the complexity of having imagery and metadata in two places. 

If sprites aren't valid in a style, just skip showing them? Easy way to point out a problem.

**Comment by tmcw** [comment]
/cc @mapbox/gl 

Can we schedule a v8 sprint directly after the gl-native code is shipped? To ship this, we need many more hands on deck.

**Comment by tmcw** [comment]
Additionally: should we fold #276 Circle render type into this issue? I'm about to sketch out an implementation in gl-js

**Comment by lbud** [comment]
Grabbing types on native.

**Comment by lbud** [comment]
@tmcw should [`validate.constants`](https://github.com/mapbox/mapbox-gl-style-spec/blob/v8/lib/validate/parsed.js#L67) also enforce that all constants have types?

**Comment by tmcw** [comment]
y, i'll implement that.

**Pull request merged**
