### PR TITLE
Move package to @mapbox namespace.

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by lucaswoj** [comment]
Thanks @tmcw & @tmcw's bash scripts. 

I think this is the workflow we'll need to get this change pushed all the way through. Anything missing here? 

# Todo

 - [ ] 🚢
 - [ ] publish this package in @mapbox namespace
 - [ ] deprecate the old non-namespaced package
 - [ ] update all internal projects that reference `mapbox-gl-style-spec`

**Comment by mourner** [comment]
How about removing the `mapbox-` prefix for less redundancy? E.g. `@mapbox/gl-style-spec` instead of `@mapbox/mapbox-gl-style-spec`.

**Comment by jfirebaugh** [comment]
If we do that, we should remove `gl` too.

**Comment by mourner** [comment]
@jfirebaugh should we also publish GL JS under `@mapbox/js`, or should it still be `@mapbox/gl-js`?

**Comment by lucaswoj** [comment]
Planning to do this at the same time as https://github.com/mapbox/mapbox-gl-js/issues/3794

**Comment by lucaswoj** [comment]
Rolling this into mapbox/mapbox-gl-js#3794 and https://github.com/mapbox/mapbox-gl-js/pull/3946

**Pull request closed without merging**
